paragraphs_paste_third_party:
  type: mapping
  label: 'Schema for Paragraphs Paste options of Paragraphs Widget'
  mapping:
    enabled:
      type: boolean
      label: 'Copy & Paste area enabled'
    mapping:
      type: mapping
      mapping:
        oembed_url:video:
          type: string
        oembed_url:twitter:
          type: string
        oembed_url:instagram:
          type: string
        text:
          type: string
    split_method:
      type: sequence
      sequence:
        type: string
    split_method_regex:
      type: string
      label: 'RegEx'

field.widget.third_party.paragraphs_paste:
  type: paragraphs_paste_third_party
